language: node_js
node_js:
  - "16.14.2"
stages:
- compile
- deploy
jobs:
  include:
    - stage: deploy
      deploy:
        provider: heroku
        app: lama-social
        api_key:
          secure: "bccab0a7-73d3-4507-9f53-96c291d5aa2a"
          # ⋮